name: 😭 Help!
description: Ask for help
title: "[HELP] <title>"
labels: help wanted
body:
- type: textarea
  attributes:
    label: A clear and concise description of what the problem is.
    description: A clear and concise description of what the problem is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
